[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/discovery/search"
  to = "/.netlify/functions/discovery-search"
  status = 200

[[redirects]]
  from = "/discovery/resources"
  to = "/.netlify/functions/discovery-resources"
  status = 200

[[redirects]]
  from = "/discovery/merchant"
  to = "/.netlify/functions/discovery-merchant"
  status = 200

[[redirects]]
  from = "/submit"
  to = "/.netlify/functions/submit"
  status = 200
